baseURL = "http://maiyayu.me/"
languageCode = "en-us"
title = "Maiya Yu"
theme = "soho"
enableInlineShortcodes = true

summarylength = 10
enableEmoji = true
googleAnalytics = "UA-170661738-1"

[params]
author = "Maiya Yu"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/maiya-pic.png"
copyright = "Maiya Yu"
license = "MIT"
licenseURL = "https://opensource.org/licenses/MIT"
## Set custom theme color.
themeColor = "#05204A"
## Set custom CSS and/or JS to override site defaults.
customCss = ["css/profile.css"]
  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/maiya-yu/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/mshyu24"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/maiya_yu"

[menu]


  [[menu.main]]
  name = "about"
  identifier = "about"
  weight = 300
  url = "/about/"

  [[menu.main]]
  name = "research"
  identifier = "research"
  weight = 300
  url = "/research/"

  [[menu.main]]
  name = "food"
  identifier = "food"
  weight = 300
  url = "/food/"

  [[menu.main]]
  name = "miscellanea"
  identifier = "miscellanea"
  weight = 300
  url = "/miscellanea/"

  [[menu.main]]
  name = "unsolicited-thoughts"
  identifier = "unsolicited-thoughts"
  weight = 300
  url = "/unsolicited-thoughts/"

  [[menu.main]]
  name = "tutoring"
  identifier = "tutoring"
  weight = 300
  url = "/tutoring/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup]

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true # if false, you need to provide you own custom CSS
style = "monokai"
tabWidth = 4
